### PR TITLE
Create simple ui

### PR DESCRIPTION
**Pull request by hh1834**

### CODE REVIEW

**Comment by zzihan1203** [comment]
Can you adjust the design for ui? We have 7 APIs.

**Comment by hh1834** [comment]
got it; I will work on it so the urls are pointing to the correct places too

**Comment by ytc338** [comment]
The buttons are not working now, in which story should we implement the functions?

**Comment by hh1834** [comment]
I think each person implementing the scenario for integration test should configure so each button linked with that api work

**Pull request merged**
